<?php

namespace Database\Seeders;

use App\Models\EducationUnit;
use App\Models\JenisUnitPendidikan;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

class DataDummyUnitPendidikanSeeder extends Seeder
{
    /**
     * Seed the application's database with dummy education units.
     */
    public function run(): void
    {
        if (JenisUnitPendidikan::count() === 0) {
            $this->call(MasterJenisUnitPendidikanSeeder::class);
        }

        $jenisUnits = JenisUnitPendidikan::all();
        $units = [
            [
                'code' => 'TKIT-01',
                'name' => 'TKIT 1 Dar el-Iman - Padang',
                'level' => 'TKIT',
                'description' => 'Taman Kanak-Kanak Islam Terpadu 1 Padang.',
                'is_active' => true,
                'metadata' => [
                    'singkatan' => 'TKIT 1',
                    'jenjang' => 'TK',
                    'city' => 'Padang',
                    'province' => 'Sumatera Barat',
                    'principal_name' => 'Ust. Rahmat Hidayat, S.Pd',
                    'phone' => '0812-1111-2222',
                    'email' => 'tkit1@dareliman.sch.id',
                    'npsn' => '10100001',
                    'address' => 'Jl. Gunuang Sarik No. 12, Kuranji, Kota Padang',
                    'postal_code' => '25154',
                    'established_year' => 2012,
                    'accreditation' => 'A',
                    'sk_pendirian' => '421.1/001/2012',
                    'tgl_sk' => '2012-05-10',
                    'total_siswa' => 320,
                    'total_guru' => 24,
                    'total_kelas' => 12,
                    'total_rombel' => 12,
                ],
            ],
            [
                'code' => 'TKIT-02',
                'name' => 'TKIT 2 Dar el-Iman - Padang',
                'level' => 'TKIT',
                'description' => 'Taman Kanak-Kanak Islam Terpadu 2 Padang.',
                'is_active' => true,
                'metadata' => [
                    'singkatan' => 'TKIT 2',
                    'jenjang' => 'TK',
                    'city' => 'Padang',
                    'province' => 'Sumatera Barat',
                    'principal_name' => 'Ustzh. Nurul Aini, S.Pd',
                    'phone' => '0812-1111-2223',
                    'email' => 'tkit2@dareliman.sch.id',
                    'npsn' => '10100002',
                    'address' => 'Jl. Bypass Km 10, Kuranji, Kota Padang',
                    'postal_code' => '25155',
                    'established_year' => 2014,
                    'accreditation' => 'A',
                    'sk_pendirian' => '421.1/002/2014',
                    'tgl_sk' => '2014-06-15',
                    'total_siswa' => 280,
                    'total_guru' => 20,
                    'total_kelas' => 10,
                    'total_rombel' => 10,
                ],
            ],
            [
                'code' => 'TKIT-03',
                'name' => 'TKIT 3 Dar el-Iman - Padang',
                'level' => 'TKIT',
                'description' => 'Taman Kanak-Kanak Islam Terpadu 3 Padang.',
                'is_active' => true,
                'metadata' => [
                    'singkatan' => 'TKIT 3',
                    'jenjang' => 'TK',
                    'city' => 'Padang',
                    'province' => 'Sumatera Barat',
                    'principal_name' => 'Ustzh. Yuliana, S.Pd',
                    'phone' => '0812-1111-2224',
                    'email' => 'tkit3@dareliman.sch.id',
                    'npsn' => '10100003',
                    'address' => 'Jl. Surau Gadang No. 4, Nanggalo, Kota Padang',
                    'postal_code' => '25143',
                    'established_year' => 2016,
                    'accreditation' => 'A',
                    'sk_pendirian' => '421.1/003/2016',
                    'tgl_sk' => '2016-08-01',
                    'total_siswa' => 250,
                    'total_guru' => 18,
                    'total_kelas' => 9,
                    'total_rombel' => 9,
                ],
            ],
            [
                'code' => 'TAUD-01',
                'name' => 'TAUD SaQu Dar el-Iman - Padang',
                'level' => 'TAUD',
                'description' => 'Tahfizh Anak Usia Dini Sahabat Quran Padang.',
                'is_active' => true,
                'metadata' => [
                    'singkatan' => 'TAUD',
                    'jenjang' => 'PAUD',
                    'city' => 'Padang',
                    'province' => 'Sumatera Barat',
                    'principal_name' => 'Ustzh. Siti Rahmah, S.Pd',
                    'phone' => '0812-1111-2225',
                    'email' => 'taud@dareliman.sch.id',
                    'npsn' => '10100004',
                    'address' => 'Jl. Khatib Sulaiman Gg. Quran, Padang Utara',
                    'postal_code' => '25136',
                    'established_year' => 2018,
                    'accreditation' => 'A',
                    'sk_pendirian' => '421.1/004/2018',
                    'tgl_sk' => '2018-03-20',
                    'total_siswa' => 190,
                    'total_guru' => 15,
                    'total_kelas' => 8,
                    'total_rombel' => 8,
                ],
            ],
            [
                'code' => 'SDIT-01',
                'name' => 'SDIT 1 Dar el-Iman - 50 Kota',
                'level' => 'SDIT',
                'description' => 'Sekolah Dasar Islam Terpadu 1 Cabang 50 Kota.',
                'is_active' => true,
                'metadata' => [
                    'singkatan' => 'SDIT 1',
                    'jenjang' => 'SD',
                    'city' => '50 Kota',
                    'province' => 'Sumatera Barat',
                    'principal_name' => 'Ust. Afrizal, S.Pd.I',
                    'phone' => '0812-1111-2226',
                    'email' => 'sdit1.50kota@dareliman.sch.id',
                    'npsn' => '70012341',
                    'address' => 'Jl. Raya Payakumbuh No. 88, Limapuluh Kota',
                    'postal_code' => '26251',
                    'established_year' => 2015,
                    'accreditation' => 'A',
                    'sk_pendirian' => '421.2/015/2015',
                    'tgl_sk' => '2015-07-01',
                    'total_siswa' => 780,
                    'total_guru' => 52,
                    'total_kelas' => 24,
                    'total_rombel' => 24,
                ],
            ],
            [
                'code' => 'SDIT-02',
                'name' => 'SDIT 2 Dar el-Iman - Padang',
                'level' => 'SDIT',
                'description' => 'Sekolah Dasar Islam Terpadu 2 Padang.',
                'is_active' => true,
                'metadata' => [
                    'singkatan' => 'SDIT 2',
                    'jenjang' => 'SD',
                    'city' => 'Padang',
                    'province' => 'Sumatera Barat',
                    'principal_name' => 'Ust. Fadli Rahman, S.Pd',
                    'phone' => '0812-3456-7890',
                    'email' => 'sdit2@dareliman.sch.id',
                    'npsn' => '70012345',
                    'address' => 'Jl. Khatib Sulaiman No. 10, Kel. Lolong Belanti, Kec. Padang Utara, Kota Padang',
                    'postal_code' => '25136',
                    'established_year' => 2011,
                    'accreditation' => 'A',
                    'sk_pendirian' => '421.3/123/DI/2011',
                    'tgl_sk' => '2011-01-12',
                    'total_siswa' => 1250,
                    'total_guru' => 95,
                    'total_kelas' => 42,
                    'total_rombel' => 48,
                ],
            ],
            [
                'code' => 'SDIT-03',
                'name' => 'SDIT 3 Dar el-Iman - Padang',
                'level' => 'SDIT',
                'description' => 'Sekolah Dasar Islam Terpadu 3 Padang.',
                'is_active' => true,
                'metadata' => [
                    'singkatan' => 'SDIT 3',
                    'jenjang' => 'SD',
                    'city' => 'Padang',
                    'province' => 'Sumatera Barat',
                    'principal_name' => 'Ust. Hendra Gunawan, S.Pd',
                    'phone' => '0812-1111-2228',
                    'email' => 'sdit3@dareliman.sch.id',
                    'npsn' => '70012346',
                    'address' => 'Jl. Ampang No. 15, Kuranji, Kota Padang',
                    'postal_code' => '25153',
                    'established_year' => 2017,
                    'accreditation' => 'A',
                    'sk_pendirian' => '421.2/017/2017',
                    'tgl_sk' => '2017-04-10',
                    'total_siswa' => 890,
                    'total_guru' => 60,
                    'total_kelas' => 30,
                    'total_rombel' => 32,
                ],
            ],
            [
                'code' => 'SDIT-04',
                'name' => 'SDIT 4 Dar el-Iman - Padang',
                'level' => 'SDIT',
                'description' => 'Sekolah Dasar Islam Terpadu 4 Padang.',
                'is_active' => true,
                'metadata' => [
                    'singkatan' => 'SDIT 4',
                    'jenjang' => 'SD',
                    'city' => 'Padang',
                    'province' => 'Sumatera Barat',
                    'principal_name' => 'Ust. Yogi Pratama, S.Pd',
                    'phone' => '0812-1111-2229',
                    'email' => 'sdit4@dareliman.sch.id',
                    'npsn' => '70012347',
                    'address' => 'Jl. Belanti Barat No. 8, Padang Utara',
                    'postal_code' => '25136',
                    'established_year' => 2020,
                    'accreditation' => 'A',
                    'sk_pendirian' => '421.2/020/2020',
                    'tgl_sk' => '2020-05-18',
                    'total_siswa' => 640,
                    'total_guru' => 45,
                    'total_kelas' => 22,
                    'total_rombel' => 24,
                ],
            ],
            [
                'code' => 'MIT-01',
                'name' => 'MIT SaQu Dar el-Iman - Padang',
                'level' => 'MIT',
                'description' => 'Madrasah Ibtidaiyah Terpadu Sahabat Quran Padang.',
                'is_active' => true,
                'metadata' => [
                    'singkatan' => 'MIT',
                    'jenjang' => 'MI',
                    'city' => 'Padang',
                    'province' => 'Sumatera Barat',
                    'principal_name' => 'Ust. Irfan Maulana, S.Pd',
                    'phone' => '0812-1111-2230',
                    'email' => 'mit@dareliman.sch.id',
                    'npsn' => '60012345',
                    'address' => 'Jl. Prof. Dr. Hamka No. 90, Air Tawar, Kota Padang',
                    'postal_code' => '25131',
                    'established_year' => 2019,
                    'accreditation' => 'A',
                    'sk_pendirian' => '421.3/019/2019',
                    'tgl_sk' => '2019-06-25',
                    'total_siswa' => 520,
                    'total_guru' => 38,
                    'total_kelas' => 18,
                    'total_rombel' => 20,
                ],
            ],
            [
                'code' => 'SMPIT-01',
                'name' => 'SMPIT 1 Dar el-Iman - Padang',
                'level' => 'SMPIT',
                'description' => 'Sekolah Menengah Pertama Islam Terpadu 1 Padang.',
                'is_active' => true,
                'metadata' => [
                    'singkatan' => 'SMPIT 1',
                    'jenjang' => 'SMP',
                    'city' => 'Padang',
                    'province' => 'Sumatera Barat',
                    'principal_name' => 'Ust. Budi Santoso, S.Pd',
                    'phone' => '0812-1111-2231',
                    'email' => 'smpit1@dareliman.sch.id',
                    'npsn' => '20101111',
                    'address' => 'Jl. Gunuang Sarik No. 50, Kuranji, Kota Padang',
                    'postal_code' => '25154',
                    'established_year' => 2013,
                    'accreditation' => 'A',
                    'sk_pendirian' => '421.3/013/2013',
                    'tgl_sk' => '2013-09-12',
                    'total_siswa' => 960,
                    'total_guru' => 70,
                    'total_kelas' => 32,
                    'total_rombel' => 36,
                ],
            ],
            [
                'code' => 'SMPIT-02',
                'name' => 'SMPIT 2 Dar el-Iman - 50 Kota',
                'level' => 'SMPIT',
                'description' => 'Sekolah Menengah Pertama Islam Terpadu 2 Cabang 50 Kota.',
                'is_active' => true,
                'metadata' => [
                    'singkatan' => 'SMPIT 2',
                    'jenjang' => 'SMP',
                    'city' => '50 Kota',
                    'province' => 'Sumatera Barat',
                    'principal_name' => 'Ust. M. Ikhsan, S.Pd',
                    'phone' => '0812-1111-2232',
                    'email' => 'smpit2.50kota@dareliman.sch.id',
                    'npsn' => '20101112',
                    'address' => 'Jl. Tanjung Pati No. 12, Limapuluh Kota',
                    'postal_code' => '26251',
                    'established_year' => 2018,
                    'accreditation' => 'A',
                    'sk_pendirian' => '421.3/018/2018',
                    'tgl_sk' => '2018-11-05',
                    'total_siswa' => 480,
                    'total_guru' => 35,
                    'total_kelas' => 16,
                    'total_rombel' => 18,
                ],
            ],
            [
                'code' => 'PONPES-PA',
                'name' => 'PONPES Putra Dar el-Iman',
                'level' => 'PONPES',
                'description' => 'Pondok Pesantren Tahfizh & Sains Putra Dar el-Iman.',
                'is_active' => true,
                'metadata' => [
                    'singkatan' => 'PONPES PA',
                    'jenjang' => 'Pondok Pesantren',
                    'city' => 'Padang Panjang',
                    'province' => 'Sumatera Barat',
                    'principal_name' => 'Ust. Dr. Muhammad Arifin, Lc., M.A',
                    'phone' => '0812-1111-2233',
                    'email' => 'ponpes.putra@dareliman.sch.id',
                    'npsn' => '50109991',
                    'address' => 'Jl. Bukit Surungan No. 1, Padang Panjang',
                    'postal_code' => '27118',
                    'established_year' => 2010,
                    'accreditation' => 'A',
                    'sk_pendirian' => '421.4/010/2010',
                    'tgl_sk' => '2010-02-14',
                    'total_siswa' => 650,
                    'total_guru' => 48,
                    'total_kelas' => 20,
                    'total_rombel' => 22,
                ],
            ],
            [
                'code' => 'PONPES-PI',
                'name' => 'PONPES Putri Dar el-Iman',
                'level' => 'PONPES',
                'description' => 'Pondok Pesantren Tahfizh & Sains Putri Dar el-Iman.',
                'is_active' => true,
                'metadata' => [
                    'singkatan' => 'PONPES PI',
                    'jenjang' => 'Pondok Pesantren',
                    'city' => 'Padang Panjang',
                    'province' => 'Sumatera Barat',
                    'principal_name' => 'Ustzh. Dr. Maryam, Lc., M.A',
                    'phone' => '0812-1111-2234',
                    'email' => 'ponpes.putri@dareliman.sch.id',
                    'npsn' => '50109992',
                    'address' => 'Jl. Silaing Bawah No. 5, Padang Panjang',
                    'postal_code' => '27118',
                    'established_year' => 2012,
                    'accreditation' => 'A',
                    'sk_pendirian' => '421.4/012/2012',
                    'tgl_sk' => '2012-10-10',
                    'total_siswa' => 580,
                    'total_guru' => 42,
                    'total_kelas' => 18,
                    'total_rombel' => 20,
                ],
            ],
            [
                'code' => 'SMAIT-01',
                'name' => 'SMAIT Dar el-Iman - Padang',
                'level' => 'SMAIT',
                'description' => 'Sekolah Menengah Atas Islam Terpadu Dar el-Iman Padang.',
                'is_active' => true,
                'metadata' => [
                    'singkatan' => 'SMAIT',
                    'jenjang' => 'SMA',
                    'city' => 'Padang',
                    'province' => 'Sumatera Barat',
                    'principal_name' => 'Ust. Ahmad Fauzi, S.Pd',
                    'phone' => '0812-1111-2235',
                    'email' => 'smait@dareliman.sch.id',
                    'npsn' => '30105555',
                    'address' => 'Jl. Gunuang Sarik No. 80, Kuranji, Kota Padang',
                    'postal_code' => '25154',
                    'established_year' => 2015,
                    'accreditation' => 'A',
                    'sk_pendirian' => '421.5/015/2015',
                    'tgl_sk' => '2015-06-01',
                    'total_siswa' => 740,
                    'total_guru' => 55,
                    'total_kelas' => 24,
                    'total_rombel' => 26,
                ],
            ],
            [
                'code' => 'MAHAD-01',
                'name' => "Mahad Abu Ja'far",
                'level' => 'MAHAD',
                'description' => "Ma'had Aly Dirasat Islamiyah Abu Ja'far Padang.",
                'is_active' => true,
                'metadata' => [
                    'singkatan' => 'MAHAD',
                    'jenjang' => 'Mahad',
                    'city' => 'Padang',
                    'province' => 'Sumatera Barat',
                    'principal_name' => 'Ust. Salman Al-Farisi, Lc.',
                    'phone' => '0812-1111-2236',
                    'email' => 'mahad@dareliman.sch.id',
                    'npsn' => '90108888',
                    'address' => 'Jl. Bypass Km 12, Kuranji, Kota Padang',
                    'postal_code' => '25155',
                    'established_year' => 2008,
                    'accreditation' => 'A',
                    'sk_pendirian' => '421.9/008/2008',
                    'tgl_sk' => '2008-01-05',
                    'total_siswa' => 410,
                    'total_guru' => 30,
                    'total_kelas' => 12,
                    'total_rombel' => 14,
                ],
            ],
        ];

        foreach ($units as $unit) {
            $levelKey = strtoupper($unit['level']);
            $jenisUnit = $jenisUnits->first(function ($item) use ($levelKey, $unit) {
                return strtoupper($item->kode_jenis) === $levelKey
                    || strtoupper($item->singkatan) === $levelKey
                    || strtoupper($item->jenjang) === $levelKey
                    || Str::slug($item->kode_jenis) === Str::slug($unit['level'])
                    || Str::slug($item->singkatan) === Str::slug($unit['level']);
            });

            if (! $jenisUnit) {
                $jenisUnit = JenisUnitPendidikan::query()
                    ->whereRaw('LOWER(kode_jenis) = ?', [strtolower($unit['level'])])
                    ->orWhereRaw('LOWER(singkatan) = ?', [strtolower($unit['level'])])
                    ->orWhereRaw('LOWER(jenjang) = ?', [strtolower($unit['level'])])
                    ->first() ?? $jenisUnits->first();
            }

            EducationUnit::query()->updateOrCreate(
                ['code' => $unit['code']],
                array_merge($unit, [
                    'jenis_unit_id' => $jenisUnit?->uuid,
                ])
            );
        }
    }
}
