<?php

namespace Database\Seeders;

use App\Models\QuranSurah;
use Illuminate\Database\Seeder;

class QuranSurahSeeder extends Seeder
{
    /**
     * Run the database seeds for 114 Surahs of Al-Qur'an.
     */
    public function run(): void
    {
        $surahs = [
            [1, 'الفاتحة', 'Al-Fatihah', 7, 'Mekah', 'Pembukaan'],
            [2, 'البقرة', 'Al-Baqarah', 286, 'Madinah', 'Sapi Betina'],
            [3, 'آل عمران', "Ali 'Imran", 200, 'Madinah', 'Keluarga Imran'],
            [4, 'النساء', "An-Nisa'", 176, 'Madinah', 'Wanita'],
            [5, 'المائدة', "Al-Ma'idah", 120, 'Madinah', 'Hidangan'],
            [6, 'الأنعام', "Al-An'am", 165, 'Mekah', 'Binatang Ternak'],
            [7, 'الأعراف', "Al-A'raf", 206, 'Mekah', 'Tempat Tertinggi'],
            [8, 'الأنفal', 'Al-Anfal', 75, 'Madinah', 'Rampasan Perang'],
            [9, 'التوبة', 'At-Taubah', 129, 'Madinah', 'Pengampunan'],
            [10, 'يونس', 'Yunus', 109, 'Mekah', 'Nabi Yunus'],
            [11, 'هود', 'Hud', 123, 'Mekah', 'Nabi Hud'],
            [12, 'يوسف', 'Yusuf', 111, 'Mekah', 'Nabi Yusuf'],
            [13, 'الرعد', "Ar-Ra'd", 43, 'Madinah', 'Guruh'],
            [14, 'إبراهيم', 'Ibrahim', 52, 'Mekah', 'Nabi Ibrahim'],
            [15, 'الحجر', 'Al-Hijr', 99, 'Mekah', 'Lembah Hijr'],
            [16, 'النحل', 'An-Nahl', 128, 'Mekah', 'Lebah'],
            [17, 'الإسراء', "Al-Isra'", 111, 'Mekah', 'Perjalanan Malam'],
            [18, 'الكهف', 'Al-Kahf', 110, 'Mekah', 'Gua'],
            [19, 'مريم', 'Maryam', 98, 'Mekah', 'Maryam'],
            [20, 'طه', 'Ta Ha', 135, 'Mekah', 'Thaha'],
            [21, 'الأنبياء', "Al-Anbiya'", 112, 'Mekah', 'Para Nabi'],
            [22, 'الحج', 'Al-Hajj', 78, 'Madinah', 'Haji'],
            [23, 'المؤمنون', "Al-Mu'minun", 118, 'Mekah', 'Orang-Orang Mukmin'],
            [24, 'النور', 'An-Nur', 64, 'Madinah', 'Cahaya'],
            [25, 'الفرقان', 'Al-Furqan', 77, 'Mekah', 'Pembeda'],
            [26, 'الشعراء', "Asy-Syu'ara'", 227, 'Mekah', 'Para Penyair'],
            [27, 'النمل', 'An-Naml', 93, 'Mekah', 'Semut'],
            [28, 'القصص', 'Al-Qasas', 88, 'Mekah', 'Kisah-Kisah'],
            [29, 'العنكبوت', "Al-'Ankabut", 69, 'Mekah', 'Laba-Laba'],
            [30, 'الروم', 'Ar-Rum', 60, 'Mekah', 'Bangsa Romawi'],
            [31, 'لقمان', 'Luqman', 34, 'Mekah', 'Luqman'],
            [32, 'السجدة', 'As-Sajdah', 30, 'Mekah', 'Sujud'],
            [33, 'الأحزاب', 'Al-Ahzab', 73, 'Madinah', 'Golongan Bersekutu'],
            [34, 'سبأ', "Saba'", 54, 'Mekah', 'Kaum Saba'],
            [35, 'فاطر', 'Fatir', 45, 'Mekah', 'Pencipta'],
            [36, 'يس', 'Ya Sin', 83, 'Mekah', 'Yasin'],
            [37, 'الصافات', 'As-Saffat', 182, 'Mekah', 'Barisan-Barisan'],
            [38, 'ص', 'Sad', 88, 'Mekah', 'Shad'],
            [39, 'الزمر', 'Az-Zumar', 75, 'Mekah', 'Rombongan'],
            [40, 'غافر', 'Ghafir', 85, 'Mekah', 'Maha Pengampun'],
            [41, 'فصلت', 'Fussilat', 54, 'Mekah', 'Yang Dijelaskan'],
            [42, 'الشورى', 'Asy-Syura', 53, 'Mekah', 'Musyawarah'],
            [43, 'الزخرف', 'Az-Zukhruf', 89, 'Mekah', 'Perhiasan'],
            [44, 'الدخان', 'Ad-Dukhan', 59, 'Mekah', 'Kabut'],
            [45, 'الجاثية', 'Al-Jasiyah', 37, 'Mekah', 'Yang Berlutut'],
            [46, 'الأحقاف', 'Al-Ahqaf', 35, 'Mekah', 'Bukit-Bukit Pasir'],
            [47, 'محمد', 'Muhammad', 38, 'Madinah', 'Nabi Muhammad'],
            [48, 'الفتح', 'Al-Fath', 29, 'Madinah', 'Kemenangan'],
            [49, 'الحجرات', 'Al-Hujurat', 18, 'Madinah', 'Kamar-Kamar'],
            [50, 'ق', 'Qaf', 45, 'Mekah', 'Qaf'],
            [51, 'الذاريات', 'Az-Zariyat', 60, 'Mekah', 'Angin Yang Menerbangkan'],
            [52, 'الطور', 'At-Tur', 49, 'Mekah', 'Bukit Tursina'],
            [53, 'النجم', 'An-Najm', 62, 'Mekah', 'Bintang'],
            [54, 'القمر', 'Al-Qamar', 55, 'Mekah', 'Bulan'],
            [55, 'الرحمن', 'Ar-Rahman', 78, 'Madinah', 'Maha Pengasih'],
            [56, 'الواقعة', "Al-Waqi'ah", 96, 'Mekah', 'Hari Kiamat'],
            [57, 'الحديد', 'Al-Hadid', 29, 'Madinah', 'Besi'],
            [58, 'المجادلة', 'Al-Mujadilah', 22, 'Madinah', 'Gugatan'],
            [59, 'الحشر', 'Al-Hasyr', 24, 'Madinah', 'Pengusiran'],
            [60, 'الممتحنة', 'Al-Mumtahanah', 13, 'Madinah', 'Wanita Yang Diuji'],
            [61, 'الصف', 'As-Saff', 14, 'Madinah', 'Barisan'],
            [62, 'الجمعة', "Al-Jumu'ah", 11, 'Madinah', 'Hari Jumat'],
            [63, 'المنافقون', 'Al-Munafiqun', 11, 'Madinah', 'Orang-Orang Munafik'],
            [64, 'التغابن', 'At-Taghabun', 18, 'Madinah', 'Hari Dinampakkan Kesalahan'],
            [65, 'الطلاق', 'At-Talaq', 12, 'Madinah', 'Talak'],
            [66, 'التحريم', 'At-Tahrim', 12, 'Madinah', 'Mengharamkan'],
            [67, 'الملك', 'Al-Mulk', 30, 'Mekah', 'Kerajaan'],
            [68, 'القلم', 'Al-Qalam', 52, 'Mekah', 'Pena'],
            [69, 'الحاقة', 'Al-Haqqah', 52, 'Mekah', 'Hari Kiamat'],
            [70, 'المعارج', "Al-Ma'arij", 44, 'Mekah', 'Tempat Naik'],
            [71, 'نوح', 'Nuh', 28, 'Mekah', 'Nabi Nuh'],
            [72, 'الجن', 'Al-Jinn', 28, 'Mekah', 'Jin'],
            [73, 'المزمل', 'Al-Muzzammil', 20, 'Mekah', 'Orang Yang Berselimut'],
            [74, 'المدثر', 'Al-Muddassir', 56, 'Mekah', 'Orang Yang Berkemul'],
            [75, 'القيامة', 'Al-Qiyamah', 40, 'Mekah', 'Hari Kiamat'],
            [76, 'الإنسان', 'Al-Insan', 31, 'Madinah', 'Manusia'],
            [77, 'المرسلات', 'Al-Mursalat', 50, 'Mekah', 'Malaikat Yang Diutus'],
            [78, 'النبأ', "An-Naba'", 40, 'Mekah', 'Berita Besar'],
            [79, 'النازعات', "An-Nazi'at", 46, 'Mekah', 'Malaikat Yang Mencabut'],
            [80, 'عبس', "'Abasa", 42, 'Mekah', 'Ia Bermuka Masam'],
            [81, 'التكوير', 'At-Takwir', 29, 'Mekah', 'Penggulungan'],
            [82, 'الانفطار', 'Al-Infitar', 19, 'Mekah', 'Terbelah'],
            [83, 'المطففين', 'Al-Mutaffifin', 36, 'Mekah', 'Orang-Orang Curang'],
            [84, 'الانشقاق', 'Al-Insiqaq', 19, 'Mekah', 'Terbelah'],
            [85, 'البروج', 'Al-Buruj', 22, 'Mekah', 'Gugusan Bintang'],
            [86, 'الطارق', 'At-Tariq', 17, 'Mekah', 'Yang Datang Di Malam Hari'],
            [87, 'الأعلى', "Al-A'la", 19, 'Mekah', 'Maha Tinggi'],
            [88, 'الغاشية', 'Al-Ghasyiyah', 26, 'Mekah', 'Hari Kiamat'],
            [89, 'الفجر', 'Al-Fajr', 30, 'Mekah', 'Fajar'],
            [90, 'البلد', 'Al-Balad', 20, 'Mekah', 'Negeri'],
            [91, 'الشمس', 'Asy-Syams', 15, 'Mekah', 'Matahari'],
            [92, 'الليل', 'Al-Lail', 21, 'Mekah', 'Malam'],
            [93, 'الضحى', 'Ad-Duha', 11, 'Mekah', 'Waktu Dhuha'],
            [94, 'الشرح', 'Asy-Syarh', 8, 'Mekah', 'Kelapangan'],
            [95, 'التين', 'At-Tin', 8, 'Mekah', 'Buah Tin'],
            [96, 'العلق', "Al-'Alaq", 19, 'Mekah', 'Segumpal Darah'],
            [97, 'القدر', 'Al-Qadr', 5, 'Mekah', 'Kemuliaan'],
            [98, 'البينة', 'Al-Bayyinah', 8, 'Madinah', 'Bukti Nyata'],
            [99, 'Zalzalah', 'Az-Zalzalah', 8, 'Madinah', 'Keguncangan'],
            [100, 'العاديات', "Al-'Adiyat", 11, 'Mekah', 'Kuda Perang'],
            [101, 'القارعة', "Al-Qari'ah", 11, 'Mekah', 'Hari Kiamat'],
            [102, 'التكاثر', 'At-Takasur', 8, 'Mekah', 'Bermegah-Megahan'],
            [103, 'العصر', "Al-'Asr", 3, 'Mekah', 'Masa/Waktu'],
            [104, 'الهمزة', 'Al-Humazah', 9, 'Mekah', 'Pengumpat'],
            [105, 'الفيل', 'Al-Fil', 5, 'Mekah', 'Gajah'],
            [106, 'قريش', 'Quraisy', 4, 'Mekah', 'Suku Quraisy'],
            [107, 'الماعون', "Al-Ma'un", 7, 'Mekah', 'Barang Berguna'],
            [108, 'الكوثر', 'Al-Kausar', 3, 'Mekah', 'Nikmat Yang Banyak'],
            [109, 'Kafirun', 'Al-Kafirun', 6, 'Mekah', 'Orang-Orang Kafir'],
            [110, 'النصر', 'An-Nasr', 3, 'Madinah', 'Pertolongan'],
            [111, 'المسد', 'Al-Lahab', 5, 'Mekah', 'Gejolak Api'],
            [112, 'الإخلاص', 'Al-Ikhlas', 4, 'Mekah', 'Ikhlas'],
            [113, 'الفلق', 'Al-Falaq', 5, 'Mekah', 'Waktu Subuh'],
            [114, 'الناس', 'An-Nas', 6, 'Mekah', 'Manusia'],
        ];

        foreach ($surahs as $item) {
            QuranSurah::updateOrCreate(
                ['nomor' => $item[0]],
                [
                    'nama' => $item[1],
                    'nama_latin' => $item[2],
                    'jumlah_ayat' => $item[3],
                    'tempat_turun' => $item[4],
                    'arti' => $item[5],
                    'deskripsi' => null,
                    'audio_full' => "https://equran.nos.wjv-1.neo.id/audio-full/Mishary-Rashid-Al-Afasy/" . sprintf("%03d", $item[0]) . ".mp3",
                ]
            );
        }
    }
}
