<?php

namespace Database\Seeders;

use App\Models\Permission;
use App\Models\Role;
use Illuminate\Database\Seeder;

class RolePermissionSeeder extends Seeder
{
    public function run(): void
    {
        $roles = [
            'Super Admin',
            'Yayasan',
            'Kepala Sekolah',
            'Wakil Kepala Sekolah',
            'Divisi Pendidikan',
            'Tata Usaha',
            'Guru',
            'Wali Kelas',
            'Ketua Yayasan',
            'Pembimbing',
            'Guru Tahfizh',
            'Guru PAI',
            'TU',
            'Musyrif',
            'Musyrifah',
            'Musyrif / Musyrifah',
            'Orang Tua',
            'Siswa',
        ];

        $permissions = [
            // Dashboard & Pemantauan
            'dashboard.view',
            'dashboard.pemantauan.lihat',
            'dashboard.pemantauan.kelola',
            'divisi.monitoring',
            'divisi.laporan_bulanan',

            // Dashboard Pengurus Yayasan (Foundation Monitoring)
            'foundation.dashboard.view',
            'foundation.unit.view',
            'foundation.employee.view',
            'foundation.teacher.view',
            'foundation.student.view',
            'foundation.student_new.view',
            'foundation.student_mutation.view',
            'foundation.graduation.view',
            'foundation.alumni.view',
            'foundation.information.view',
            'foundation.report.view',
            'foundation.report.export',
            'foundation.notification.view',
            'foundation.notification.read',
            'foundation.notification.read_all',
            'foundation.profile.view',
            'foundation.profile.update',
            'foundation.profile.change_password',

            // Kehadiran & Absensi Siswa
            'kehadiran.siswa.monitoring',
            'kehadiran.siswa.absensi_digital',
            'kehadiran.siswa.rekap_keterlambatan',
            'kehadiran.siswa.rekap_ketidakhadiran',
            'kehadiran.siswa.barcode_kartu',
            'kehadiran.siswa.izin_sakit',

            // Presensi Pembelajaran berbasis jadwal (permission baru, permission lama dipertahankan)
            'lesson_attendance.view',
            'lesson_attendance.view_own',
            'lesson_attendance.create',
            'lesson_attendance.update',
            'lesson_attendance.finalize',
            'lesson_attendance.unlock',
            'lesson_attendance.cancel',
            'lesson_attendance.correct',
            'lesson_attendance.export',
            'homeroom_attendance.dashboard',
            'homeroom_attendance.view',
            'homeroom_attendance.follow_up',
            'homeroom_attendance.verify_permission',
            'homeroom_attendance.export',
            'student_attendance.view_own',
            'student_attendance.permission.create',
            'student_attendance.permission.update',
            'student_attendance.permission.cancel',
            'lesson_attendance.manual',
            'lesson_attendance.qr_scan',
            'lesson_attendance.barcode_scan',
            'lesson_attendance.face_scan',
            'lesson_attendance.fingerprint_scan',
            'lesson_attendance.session.start',
            'lesson_attendance.session.close',
            'lesson_attendance.scan_logs.view',
            'attendance_device.view',
            'attendance_device.manage',
            'attendance_device.receive_event',

            // Tahfizh & Mutabaah
            'tahfizh.monitoring_target',
            'tahfizh.input_setoran_harian',
            'tahfizh.hitung_baris',
            'tahfizh.rekap_harian',
            'tahfizh.rekap_mingguan',
            'tahfizh.rekap_bulanan',
            'tahfizh.rekap_tahunan',
            'tahfizh.mutabaah_yaumiyah',
            'tahfizh.laporan_target',
            'tahfizh.perhitungan_tercapai',
            'tahfizh.hafalan_terbanyak',
            'tahfizh.total_hafalan',
            'mutabaah.view',
            'mutabaah.create',
            'mutabaah.update',
            'mutabaah.delete',
            'mutabaah.restore',
            'mutabaah.daily.reopen',
            'mutabaah.export',
            'mutabaah.import',
            'mutabaah.approve',
            'mutabaah.print',
            'mutabaah.input',
            'mutabaah.agenda.manage',
            'mutabaah.dashboard.view',
            'mutabaah.category.view', 'mutabaah.category.create', 'mutabaah.category.update', 'mutabaah.category.delete', 'mutabaah.category.restore',
            'mutabaah.agenda.view', 'mutabaah.agenda.create', 'mutabaah.agenda.update', 'mutabaah.agenda.delete', 'mutabaah.agenda.restore',
            'mutabaah.template.view', 'mutabaah.template.create', 'mutabaah.template.update', 'mutabaah.template.delete', 'mutabaah.template.assign',
            'mutabaah.supervisor.view', 'mutabaah.supervisor.create', 'mutabaah.supervisor.update', 'mutabaah.supervisor.delete',
            'mutabaah.daily.view', 'mutabaah.daily.input', 'mutabaah.daily.update', 'mutabaah.daily.finalize', 'mutabaah.daily.reopen',
            'mutabaah.recap.view', 'mutabaah.report.view', 'mutabaah.report.export',
            'mutabaah.parent.monitor', 'mutabaah.parent.sign',

            // Kesiswaan & Kelulusan
            'kesiswaan.rekap_prestasi',
            'kesiswaan.kelulusan_per_unit',
            'kesiswaan.kelulusan_per_tahun',
            'kesiswaan.alumni_tujuan_lanjut',
            'kesiswaan.data_lengkap_siswa',
            'kesiswaan.kelas_rombel',
            'kesiswaan.laporan_masuk_keluar',
            'kesiswaan.penugasan_siswa',
            'kesiswaan.catatan_siswa',

            // Pembelajaran & Kurikulum
            'pembelajaran.kurikulum.view',
            'pembelajaran.kurikulum.create',
            'pembelajaran.kurikulum.edit',
            'pembelajaran.kurikulum.delete',
            'pembelajaran.kurikulum.restore',
            'pembelajaran.kurikulum.export',
            'pembelajaran.kurikulum.import',
            'pembelajaran.materi',
            'pembelajaran.kisi_kisi_ujian',
            'pembelajaran.bank_soal',
            'pembelajaran.jadwal_pelajaran',
            'pembelajaran.kalender_pendidikan',

            // Informasi Sekolah & Data Pribadi
            'sekolah.data_pribadi_siswa',
            'sekolah.informasi_sekolah',

            // Administrasi sistem (khusus Super Admin)
            'sistem.hak_akses',
            'sistem.pengaturan',
            'sistem.master_data',

            // Portal Guru
            'teacher.dashboard.view',
            'teacher.schedule.view',
            'teacher.attendance.view',
            'teacher.attendance.create',
            'teacher.attendance.update',
            'teacher.material.view',
            'teacher.material.create',
            'teacher.material.update',
            'teacher.material.delete',
            'teacher.assignment.view',
            'teacher.assignment.create',
            'teacher.assignment.update',
            'teacher.assignment.delete',
            'teacher.submission.view',
            'teacher.grade.view',
            'teacher.grade.create',
            'teacher.grade.update',
            'teacher.tahfizh.view',
            'teacher.tahfizh.create',
            'teacher.tahfizh.update',
            'teacher.mutabaah.view',
            'teacher.mutabaah.create',
            'teacher.mutabaah.update',
            'teacher.student_note.view',
            'teacher.student_note.create',
            'teacher.student_note.update',

            // Portal Orang Tua
            'parent.portal.view',
            'parent.child.view',
            'parent.attendance.view',
            'parent.permission.create',
            'parent.assignment.view',
            'parent.grade.view',
            'parent.tahfizh.view',
            'parent.mutabaah.view',
            'parent.notification.view',

            // Portal Siswa
            'student.portal.view',
            'student.profile.view',
            'student.attendance.view',
            'student.material.view',
            'student.assignment.view',
            'student.submission.create',
            'student.submission.update',
            'student.grade.view',
            'student.tahfizh.view',
            'student.mutabaah.view',
            'student.mutabaah.create',
            'student.notification.view',
            // Komunikasi Sekolah & Chat Guru
            'chat.conversation.view',
            'chat.conversation.create',
            'chat.conversation.archive',
            'chat.message.view',
            'chat.message.send',
            'chat.message.read',
            'chat.message.attachment',
            'chat.homeroom.view',
            'chat.subject_teacher.view',
            'chat.analytics.view',
            'chat.configuration.manage',
        ];

        foreach ($permissions as $permissionName) {
            Permission::query()->firstOrCreate([
                'name' => $permissionName,
                'guard_name' => 'web',
            ]);
        }

        $rolePermissionMap = [
            'Super Admin' => $permissions,
            'Kepala Sekolah' => [
                'dashboard.view',
                'dashboard.pemantauan.lihat',
                'dashboard.pemantauan.kelola',
                'divisi.monitoring',
                'divisi.laporan_bulanan',
                'kehadiran.siswa.monitoring',
                'kehadiran.siswa.absensi_digital',
                'kehadiran.siswa.rekap_keterlambatan',
                'kehadiran.siswa.rekap_ketidakhadiran',
                'tahfizh.monitoring_target',
                'tahfizh.input_setoran_harian',
                'tahfizh.hitung_baris',
                'tahfizh.rekap_harian',
                'tahfizh.rekap_mingguan',
                'tahfizh.rekap_bulanan',
                'tahfizh.rekap_tahunan',
                'tahfizh.mutabaah_yaumiyah',
                'tahfizh.perhitungan_tercapai',
                'tahfizh.hafalan_terbanyak',
                'tahfizh.total_hafalan',
                'kesiswaan.rekap_prestasi',
                'kesiswaan.kelulusan_per_unit',
                'kesiswaan.kelulusan_per_tahun',
                'kesiswaan.alumni_tujuan_lanjut',
                'kesiswaan.data_lengkap_siswa',
                'kesiswaan.kelas_rombel',
                'kesiswaan.laporan_masuk_keluar',
                'kesiswaan.penugasan_siswa',
                'kesiswaan.catatan_siswa',
                'pembelajaran.materi',
                'pembelajaran.kisi_kisi_ujian',
                'pembelajaran.bank_soal',
                'pembelajaran.jadwal_pelajaran',
                'pembelajaran.kalender_pendidikan',
            ],
            'Yayasan' => [
                'dashboard.view',
                'dashboard.pemantauan.lihat',
                'divisi.monitoring',
                'divisi.laporan_bulanan',
                'kesiswaan.rekap_prestasi',
                'kesiswaan.kelulusan_per_tahun',
            ],
            'Divisi Pendidikan' => [
                'dashboard.view',
                'dashboard.pemantauan.lihat',
                'dashboard.pemantauan.kelola',
                'divisi.monitoring',
                'divisi.laporan_bulanan',
                'kesiswaan.rekap_prestasi',
                'tahfizh.monitoring_target',
                'tahfizh.input_setoran_harian',
                'tahfizh.hitung_baris',
                'tahfizh.rekap_harian',
                'tahfizh.rekap_mingguan',
                'tahfizh.rekap_bulanan',
                'tahfizh.rekap_tahunan',
                'tahfizh.mutabaah_yaumiyah',
                'tahfizh.perhitungan_tercapai',
                'tahfizh.hafalan_terbanyak',
                'tahfizh.total_hafalan',
                'kesiswaan.kelulusan_per_unit',
                'kesiswaan.kelulusan_per_tahun',
                'kesiswaan.alumni_tujuan_lanjut',
                'kesiswaan.data_lengkap_siswa',
                'kesiswaan.kelas_rombel',
                'kesiswaan.laporan_masuk_keluar',
                'pembelajaran.jadwal_pelajaran',
                'pembelajaran.kalender_pendidikan',
            ],
            'Tata Usaha' => [
                'dashboard.view',
                'kehadiran.siswa.absensi_digital',
                'kehadiran.siswa.rekap_keterlambatan',
                'kehadiran.siswa.rekap_ketidakhadiran',
                'kesiswaan.kelulusan_per_tahun',
                'kesiswaan.alumni_tujuan_lanjut',
                'kesiswaan.penugasan_siswa',
                'kesiswaan.catatan_siswa',
                'pembelajaran.materi',
                'pembelajaran.kisi_kisi_ujian',
                'pembelajaran.bank_soal',
                'pembelajaran.jadwal_pelajaran',
                'pembelajaran.kalender_pendidikan',
            ],
            'Guru' => [
                'dashboard.view',
                'tahfizh.monitoring_target',
                'tahfizh.input_setoran_harian',
                'tahfizh.hitung_baris',
                'tahfizh.rekap_harian',
                'tahfizh.rekap_mingguan',
                'tahfizh.rekap_bulanan',
                'tahfizh.rekap_tahunan',
                'tahfizh.mutabaah_yaumiyah',
                'tahfizh.perhitungan_tercapai',
                'tahfizh.hafalan_terbanyak',
                'tahfizh.total_hafalan',
                'lesson_attendance.view_own',
                'lesson_attendance.create',
                'lesson_attendance.update',
                'lesson_attendance.finalize',
                'lesson_attendance.cancel',
                'lesson_attendance.correct',
                'lesson_attendance.export',
                'lesson_attendance.manual',
                'lesson_attendance.qr_scan',
                'lesson_attendance.barcode_scan',
                'lesson_attendance.face_scan',
                'lesson_attendance.fingerprint_scan',
                'lesson_attendance.session.start',
                'lesson_attendance.session.close',
                'lesson_attendance.scan_logs.view',
                'chat.conversation.view',
                'chat.message.view',
                'chat.message.send',
                'chat.message.read',
                'chat.message.attachment',
                'chat.subject_teacher.view',
            ],
            'Wali Kelas' => [
                'dashboard.view',
                'kehadiran.siswa.monitoring',
                'kehadiran.siswa.absensi_digital',
                'tahfizh.monitoring_target',
                'tahfizh.input_setoran_harian',
                'tahfizh.hitung_baris',
                'tahfizh.rekap_harian',
                'tahfizh.rekap_mingguan',
                'tahfizh.rekap_bulanan',
                'tahfizh.rekap_tahunan',
                'tahfizh.mutabaah_yaumiyah',
                'kesiswaan.penugasan_siswa',
                'kesiswaan.catatan_siswa',
                'pembelajaran.materi',
                'pembelajaran.jadwal_pelajaran',
                'homeroom_attendance.dashboard',
                'homeroom_attendance.view',
                'homeroom_attendance.follow_up',
                'homeroom_attendance.verify_permission',
                'homeroom_attendance.export',
                'lesson_attendance.correct',
                'chat.conversation.view',
                'chat.message.view',
                'chat.message.send',
                'chat.message.read',
                'chat.message.attachment',
                'chat.homeroom.view',
            ],
            'Orang Tua' => [
                'dashboard.view',
                'parent.portal.view',
                'parent.child.view',
                'parent.attendance.view',
                'parent.permission.create',
                'parent.assignment.view',
                'parent.grade.view',
                'parent.tahfizh.view',
                'parent.mutabaah.view',
                'parent.notification.view',
                'kehadiran.siswa.barcode_kartu',
                'kehadiran.siswa.izin_sakit',
                'tahfizh.laporan_target',
                'sekolah.data_pribadi_siswa',
                'sekolah.informasi_sekolah',
                'kesiswaan.penugasan_siswa',
                'pembelajaran.materi',
                'pembelajaran.kisi_kisi_ujian',
                'pembelajaran.bank_soal',
                'chat.conversation.view',
                'chat.conversation.create',
                'chat.message.view',
                'chat.message.send',
                'chat.message.read',
                'chat.message.attachment',
                'chat.homeroom.view',
                'chat.subject_teacher.view',
            ],
            'Siswa' => [
                'dashboard.view',
                'student.portal.view',
                'student.profile.view',
                'student.attendance.view',
                'student.material.view',
                'student.assignment.view',
                'student.submission.create',
                'student.submission.update',
                'student.grade.view',
                'student.tahfizh.view',
                'student.mutabaah.view',
                'student.mutabaah.create',
                'student.notification.view',
                'kehadiran.siswa.barcode_kartu',
                'kehadiran.siswa.izin_sakit',
                'tahfizh.laporan_target',
                'sekolah.data_pribadi_siswa',
                'sekolah.informasi_sekolah',
                'kesiswaan.penugasan_siswa',
                'pembelajaran.materi',
                'pembelajaran.kisi_kisi_ujian',
                'pembelajaran.bank_soal',
                'student_attendance.view_own',
                'student_attendance.permission.create',
                'student_attendance.permission.update',
                'student_attendance.permission.cancel',
            ],
        ];

        $foundationPerms = [
            'dashboard.view',
            'foundation.dashboard.view',
            'foundation.unit.view',
            'foundation.employee.view',
            'foundation.teacher.view',
            'foundation.student.view',
            'foundation.student_new.view',
            'foundation.student_mutation.view',
            'foundation.graduation.view',
            'foundation.alumni.view',
            'foundation.information.view',
            'foundation.report.view',
            'foundation.report.export',
            'foundation.notification.view',
            'foundation.notification.read',
            'foundation.notification.read_all',
            'foundation.profile.view',
            'foundation.profile.update',
            'foundation.profile.change_password',
        ];
        $readAll = ['mutabaah.dashboard.view', 'mutabaah.recap.view', 'mutabaah.report.view', 'mutabaah.report.export'];
        foreach (['Ketua Yayasan', 'Yayasan', 'ketua_yayasan', 'sekretaris_yayasan', 'bendahara_yayasan', 'pengurus_yayasan'] as $roleName) {
            $rolePermissionMap[$roleName] = array_values(array_unique(array_merge($rolePermissionMap[$roleName] ?? ['dashboard.view'], $readAll, $foundationPerms)));
        }
        $rolePermissionMap['Kepala Sekolah'] = array_values(array_unique(array_merge($rolePermissionMap['Kepala Sekolah'], [
            ...$readAll, 'mutabaah.supervisor.view', 'mutabaah.parent.monitor',
        ])));
        $tuPermissions = [
            'mutabaah.dashboard.view', 'mutabaah.recap.view', 'mutabaah.report.view', 'mutabaah.report.export', 'mutabaah.parent.monitor',
            'mutabaah.category.view', 'mutabaah.category.create', 'mutabaah.category.update', 'mutabaah.category.delete', 'mutabaah.category.restore',
            'mutabaah.agenda.view', 'mutabaah.agenda.create', 'mutabaah.agenda.update', 'mutabaah.agenda.delete', 'mutabaah.agenda.restore',
            'mutabaah.template.view', 'mutabaah.template.create', 'mutabaah.template.update', 'mutabaah.template.delete', 'mutabaah.template.assign',
            'mutabaah.supervisor.view', 'mutabaah.supervisor.create', 'mutabaah.supervisor.update', 'mutabaah.supervisor.delete',
        ];
        foreach (['Tata Usaha', 'TU'] as $roleName) {
            $rolePermissionMap[$roleName] = array_values(array_unique(array_merge($rolePermissionMap[$roleName] ?? ['dashboard.view'], $tuPermissions)));
        }
        $dailyPermissions = ['mutabaah.daily.view', 'mutabaah.daily.input', 'mutabaah.daily.update', 'mutabaah.daily.finalize', 'mutabaah.recap.view'];
        foreach (['Guru', 'Wali Kelas', 'Pembimbing', 'Guru PAI', 'Guru Tahfizh', 'Musyrif', 'Musyrifah'] as $roleName) {
            $rolePermissionMap[$roleName] = array_values(array_unique(array_merge($rolePermissionMap[$roleName] ?? ['dashboard.view'], $dailyPermissions)));
        }
        $rolePermissionMap['Orang Tua'] = array_values(array_unique(array_merge($rolePermissionMap['Orang Tua'], ['mutabaah.daily.view', 'mutabaah.parent.sign'])));
        $rolePermissionMap['Siswa'] = array_values(array_unique(array_merge($rolePermissionMap['Siswa'], ['mutabaah.daily.view'])));

        foreach ($roles as $roleName) {
            $role = Role::query()->firstOrCreate([
                'name' => $roleName,
                'guard_name' => 'web',
            ]);

            if ($roleName !== 'Super Admin' && isset($rolePermissionMap[$roleName])) {
                $role->syncPermissions($rolePermissionMap[$roleName]);
            }
        }

        // Super Admin wajib memiliki seluruh permission tanpa terkecuali
        $superAdminRole = Role::query()->firstOrCreate([
            'name' => 'Super Admin',
            'guard_name' => 'web',
        ]);
        $superAdminRole->syncPermissions(
            Permission::where('guard_name', 'web')->get()
        );
    }
}
