import { useCallback, useEffect, useMemo, useState } from 'react'
import { CalendarRange, CheckCircle2, Clock3, RefreshCw, Search, ShieldAlert } from 'lucide-react'
import { attendanceDashboardService } from '../../services/attendance/attendanceDashboardService'
import { MasterActionButton, MasterDataPage, MasterEmptyState, MasterErrorState, MasterPageHeader, MasterStatCard, MasterStatsGrid } from '../../components/master-data'

const unwrap = (response) => response?.data?.data || response?.data || []
const formatDate = (value) => value ? new Intl.DateTimeFormat('id-ID', { dateStyle: 'medium' }).format(new Date(value)) : '-'

export default function StudentAttendanceHistoryPage() {
  const now = new Date(), first = new Date(now.getFullYear(), now.getMonth(), 1).toISOString().slice(0,10)
  const [filters,setFilters] = useState({ date_from:first, date_to:now.toISOString().slice(0,10), status:'' })
  const [records,setRecords] = useState([]), [loading,setLoading] = useState(true), [error,setError] = useState('')
  const load = useCallback(()=>{setLoading(true);setError('');attendanceDashboardService.getStudentAttendance({...filters,per_page:100}).then(r=>setRecords(unwrap(r))).catch(e=>setError(e.response?.data?.message||'Riwayat belum dapat dimuat.')).finally(()=>setLoading(false))},[filters])
  useEffect(load,[load])
  const filtered = useMemo(()=>records.filter(item=>{const d=String(item.tanggal||item.created_at||'').slice(0,10),s=String(item.status_hadir||item.status||'').toLowerCase();return (!filters.date_from||d>=filters.date_from)&&(!filters.date_to||d<=filters.date_to)&&(!filters.status||s===filters.status)}),[records,filters])
  const counts=useMemo(()=>Object.fromEntries(['hadir','terlambat','izin','sakit','alpa'].map(s=>[s,filtered.filter(i=>String(i.status_hadir||i.status).toLowerCase()===s).length])),[filtered])
  return <MasterDataPage className="education-unit-page attendance-student-page" hideBreadcrumb>
    <MasterPageHeader title="Riwayat Kehadiran" description="Telusuri rekap presensi berdasarkan periode, mata pelajaran, dan status kehadiran." tone="brand" icon={CalendarRange} actions={<MasterActionButton className="education-unit-hero__action !h-11 !border-white !bg-white !text-emerald-800" icon={RefreshCw} onClick={load}>Muat Ulang</MasterActionButton>} />
    <MasterStatsGrid className="education-unit-kpis">
      <MasterStatCard icon={CalendarRange} label="Total Catatan" value={filtered.length} description="Sesuai filter aktif" variant="info" />
      <MasterStatCard icon={CheckCircle2} label="Hadir" value={counts.hadir} description="Kehadiran tepat waktu" variant="success" />
      <MasterStatCard icon={Clock3} label="Terlambat" value={counts.terlambat} description="Tercatat terlambat" variant="warning" />
      <MasterStatCard icon={ShieldAlert} label="Tidak Hadir" value={counts.izin+counts.sakit+counts.alpa} description="Izin, sakit, dan alpa" variant="danger" />
    </MasterStatsGrid>
    <section className="rounded-[18px] border border-slate-200/80 bg-white p-4 shadow-sm dark:border-slate-700 dark:bg-[#1B2433]" aria-label="Filter riwayat kehadiran"><div className="flex items-center gap-2 overflow-x-auto pb-1"><span className="inline-flex h-11 shrink-0 items-center gap-2 rounded-xl border border-slate-200 px-3 text-xs font-bold text-slate-500 dark:border-slate-700"><Search className="h-4 w-4 text-emerald-700"/>Filter</span><label className="sr-only" htmlFor="attendance-from">Tanggal mulai</label><input id="attendance-from" type="date" value={filters.date_from} onChange={e=>setFilters({...filters,date_from:e.target.value})} className="h-11 shrink-0 rounded-xl border border-slate-200 bg-transparent px-3 text-xs dark:border-slate-700"/><label className="sr-only" htmlFor="attendance-to">Tanggal akhir</label><input id="attendance-to" type="date" value={filters.date_to} onChange={e=>setFilters({...filters,date_to:e.target.value})} className="h-11 shrink-0 rounded-xl border border-slate-200 bg-transparent px-3 text-xs dark:border-slate-700"/><select aria-label="Filter status kehadiran" value={filters.status} onChange={e=>setFilters({...filters,status:e.target.value})} className="h-11 shrink-0 rounded-xl border border-slate-200 bg-transparent px-3 text-xs dark:border-slate-700"><option value="">Semua status</option>{['hadir','terlambat','izin','sakit','alpa'].map(s=><option key={s} value={s}>{s[0].toUpperCase()+s.slice(1)}</option>)}</select></div></section>
    <section className="overflow-hidden rounded-[18px] border border-slate-200/80 bg-white shadow-sm dark:border-slate-700 dark:bg-[#1B2433]"><div className="flex items-center justify-between border-b px-5 py-4 dark:border-slate-700"><div><h2 className="text-base font-bold">Daftar Riwayat</h2><p className="mt-0.5 text-xs text-slate-500">Data presensi sesuai periode yang dipilih.</p></div><span className="rounded-full bg-emerald-50 px-3 py-1 text-xs font-bold text-emerald-800 dark:bg-emerald-950 dark:text-emerald-300">{filtered.length} catatan</span></div>{error?<div className="p-5"><MasterErrorState description={error} onRetry={load}/></div>:loading?<div className="space-y-3 p-5">{[1,2,3,4].map(i=><div key={i} className="h-14 animate-pulse rounded-xl bg-slate-100 dark:bg-slate-800"/>)}</div>:filtered.length?<div className="divide-y divide-slate-100 dark:divide-slate-800">{filtered.map(i=><div key={i.id} className="grid gap-2 p-4 text-sm transition hover:bg-emerald-50/40 dark:hover:bg-emerald-950/20 sm:grid-cols-[140px_1fr_140px]"><b>{formatDate(i.tanggal||i.created_at)}</b><span>{i.jadwal_pelajaran?.subject?.name||i.session?.subject?.name||'Mata Pelajaran'}</span><span className="capitalize font-bold text-emerald-700 dark:text-emerald-300">{i.status_hadir||i.status}</span></div>)}</div>:<div className="p-5"><MasterEmptyState title="Riwayat Tidak Ditemukan" description="Ubah periode atau status untuk melihat data lainnya."/></div>}</section>
  </MasterDataPage>
}
